// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxjW0oL4aZ53cThO-ablcizyYwTiEpbMs',
    appId: '1:735774446205:web:e03e99547802c088a1d714',
    messagingSenderId: '735774446205',
    projectId: 'probuy-728a9',
    authDomain: 'probuy-728a9.firebaseapp.com',
    storageBucket: 'probuy-728a9.appspot.com',
    measurementId: 'G-EGEEXNHT75',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHMHSpF8-2SXAHIXQUfyKVIivUvrJV7d8',
    appId: '1:735774446205:android:08191c986c53ca07a1d714',
    messagingSenderId: '735774446205',
    projectId: 'probuy-728a9',
    storageBucket: 'probuy-728a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrfpExpf4eaYpCDJGtDLHY8K19OsJ_U70',
    appId: '1:735774446205:ios:cff80c93d50ea56ba1d714',
    messagingSenderId: '735774446205',
    projectId: 'probuy-728a9',
    storageBucket: 'probuy-728a9.appspot.com',
    iosBundleId: 'com.pro.proBuy',
  );
}
